"""empty message

Revision ID: 2049007e2045
Revises: e511460269fd
Create Date: 2021-04-18 15:05:38.315846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2049007e2045'
down_revision = 'e511460269fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shijian', sa.Text(length=200), nullable=False),
    sa.Column('pinlei', sa.Text(length=200), nullable=False),
    sa.Column('zhibiao', sa.Text(length=200), nullable=False),
    sa.Column('diqu', sa.Text(length=200), nullable=False),
    sa.Column('danwei', sa.Text(length=200), nullable=False),
    sa.Column('shuzhi', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wheat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shijian', mysql.TEXT(), nullable=False),
    sa.Column('pinlei', mysql.TEXT(), nullable=False),
    sa.Column('zhibiao', mysql.TEXT(), nullable=False),
    sa.Column('diqu', mysql.TEXT(), nullable=False),
    sa.Column('danwei', mysql.TEXT(), nullable=False),
    sa.Column('shuzhi', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('grain')
    # ### end Alembic commands ###
