"""empty message

Revision ID: e511460269fd
Revises: 737d86450cec
Create Date: 2021-04-15 22:06:15.781985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e511460269fd'
down_revision = '737d86450cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shijian', sa.Text(length=200), nullable=False),
    sa.Column('pinlei', sa.Text(length=200), nullable=False),
    sa.Column('zhibiao', sa.Text(length=200), nullable=False),
    sa.Column('diqu', sa.Text(length=200), nullable=False),
    sa.Column('danwei', sa.Text(length=200), nullable=False),
    sa.Column('shuzhi', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheat')
    # ### end Alembic commands ###
